###Create Tests
Post http://localhost:4500/test/create
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "title": "zizion's second test.",
    "introduction": "this is the second exam that zizion is creating",
    "questions": {
        "questionText": "Question no.2",
        "answerOptions": ["a", "b", "c"],
        "correctAnswer": "d"
    }
}

###Edit a Test by ID
Post http://localhost:4500/test/edit/63df80a15d8bea18c85a1be5
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "title": "zizion's 3rd test",
    "introduction": "",
    "questions": {
        "questionText": "question1",
        "answerOptions": ["a", "b", "c"],
        "correctAnswer": "d"
    },
    "public": "false"

}

###Delete a Test by ID
Delete http://localhost:4500/test/delete/63df82370707a1889f726c2b
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

###Delete a question by ID
Delete http://localhost:4500/test/deletedeleteQuestions/
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

###Show a Test by ID
Get http://localhost:4500/test/63df82370707a1889f726c2b
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}