###User Profile - This section only works in swagger UI
Get http://localhost:4500/user/profile
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

###Update User Profile
Post http://localhost:4500/user/editProfile
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username": "zizion",
    "email": "zeinabjafari99@gmail.com",
    "mobile": ""
}

###User's Tests
Get http://localhost:4500/user/tests
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}