###User Profile
Get http://localhost:4500/user/profile
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

###Update User Profile
Post http://localhost:4500/user/editProfile
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}

{
    "username": "zeinabdastjerdi22",
    "email": "zizdastjerdi@gmail.com",
    "mobile": "09964315286"
}

###User's Tests
Get http://localhost:4500/user/tests
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}